# Generated by Django 3.0 on 2020-01-10 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('bedrooms', models.IntegerField()),
                ('bathroom', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('sqrt', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.TextField()),
                ('listing_date', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('main_photo', models.ImageField(blank=True, upload_to='photo/')),
                ('main1', models.ImageField(blank=True, upload_to='photo/')),
                ('main2', models.ImageField(blank=True, upload_to='photo/')),
                ('main3', models.ImageField(blank=True, upload_to='photo/')),
                ('main4', models.ImageField(blank=True, upload_to='photo/')),
                ('main5', models.ImageField(blank=True, upload_to='photo/')),
                ('main6', models.ImageField(blank=True, upload_to='photo/')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtor.Realtor')),
            ],
        ),
    ]
