# Generated by Django 3.0 on 2020-02-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='main_photo',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
